spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wazeem
    password: wazeem998
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0









